INTENTS = {
    "product_recommendation": [
        "what moisturizer works for oily skin",
        "recommend a good cleanser",
        "what's good for sensitive skin",
        "suggest a serum for dry skin",
        "I need something for acne",
        "what should I use for dark spots",
        "best sunscreen for my skin type",
        "can you recommend a product",
        "help me find the best face wash for my skin",
        "help me pick a good cleanser",
        "what's the best product for my skin type",
        "I'm looking for something to help with my skin",
        "can you help me find a good moisturizer",
    ],
    "product_comparison": [
        "compare this serum and that one",
        "which is better, X or Y",
        "what's the difference between these two products",
        "should I get the cleanser or the gel",
        "X vs Y which one",
        "is the Vitamin C serum better than the Niacinamide one",
        "compare these two and tell me which is more suitable for my skin type",
        "which of these two would work better for my skin",
        "compare them based on price and rating and tell me which is best for me",
        "between these two options which one suits my skin type more",
    ],
    "order_tracking": [
        "where is my order",
        "track my package",
        "has my order shipped yet",
        "when will my order arrive",
        "I haven't received my package",
        "what's the status of my order",
        "order hasn't arrived",
    ],
    "return_policy": [
        "how do I return this product",
        "what is your return policy",
        "can I exchange this item",
        "I want to send this back",
        "how many days do I have to return something",
        "this product doesn't work for me, can I return it",
    ],
    "payment_issue": [
        "my payment failed",
        "card got charged twice",
        "checkout isn't working",
        "payment declined",
        "refund not received",
        "I was charged but order shows nothing",
        "having trouble paying",
    ],
}